export enum ConverterActions {
    SET_BASE_CUR = 'SET_BASE_CUR',
    SET_AMOUNT_TO_CONV = 'SET_AMOUNT_TO_CONV',
    SET_CONV_CUR = 'SET_CONV_CUR',
    SET_CONV_AMOUNT = 'SET_CONV_AMOUNT',
    SET_DAILY_RATE = 'SET_DAILY_RATE'
}